// Generated by CoffeeScript 2.5.1
(function() {
  var app;

  app = angular.module('app', ['ngRoute']);

  app.config([
    '$routerProvider',
    function($routerProvider) {
      return $routerProvider.when('/home',
    {
        templateUrl: '/component/home/homecomponent.html'
      }).when('/contact',
    {
        templateUrl: '/component/contact/contactcomponent.html'
      }).when('./blog',
    {
        templateUrl: '/component/blog/blogcomponent.html'
      }).otherwise({
        redirectTO: '/home'
      });
    }
  ]);

}).call(this);
